var knownDevices = {
    "screen": {
        "deviceName": "Screen",
        "description": "Screen display device. 128 channels",
        "paperSpeed": 1,
        "minDistBetweenNotes": 15.0,
        "channelHeight": 15.0,
        "eventHeight": 15.0,
        "eventWidth": 15.0,
        "topPadding": 20.0,
        "rightPadding": 50.0,
        "bottomPadding": 20.0,
        "leftPadding": 50.0,
        "units": "px",
        "validChannels": [
            {"noteNumber": 0, "name": "C0" ,"description": ""},
            {"noteNumber": 1, "name": "C#0" ,"description": ""},
            {"noteNumber": 2, "name": "D0" ,"description": ""},
            {"noteNumber": 3, "name": "D#0" ,"description": ""},
            {"noteNumber": 4, "name": "E0" ,"description": ""},
            {"noteNumber": 5, "name": "F0" ,"description": ""},
            {"noteNumber": 6, "name": "F#0" ,"description": ""},
            {"noteNumber": 7, "name": "G0" ,"description": ""},
            {"noteNumber": 8, "name": "G#0" ,"description": ""},
            {"noteNumber": 9, "name": "A0" ,"description": ""},
            {"noteNumber": 10, "name": "A#0" ,"description": ""},
            {"noteNumber": 11, "name": "B0" ,"description": ""},
            {"noteNumber": 12, "name": "C1" ,"description": ""},
            {"noteNumber": 13, "name": "C#1" ,"description": ""},
            {"noteNumber": 14, "name": "D1" ,"description": ""},
            {"noteNumber": 15, "name": "D#1" ,"description": ""},
            {"noteNumber": 16, "name": "E1" ,"description": ""},
            {"noteNumber": 17, "name": "F1" ,"description": ""},
            {"noteNumber": 18, "name": "F#1" ,"description": ""},
            {"noteNumber": 19, "name": "G1" ,"description": ""},
            {"noteNumber": 20, "name": "G#1" ,"description": ""},
            {"noteNumber": 21, "name": "A1" ,"description": ""},
            {"noteNumber": 22, "name": "A#1" ,"description": ""},
            {"noteNumber": 23, "name": "B1" ,"description": ""},
            {"noteNumber": 24, "name": "C2" ,"description": ""},
            {"noteNumber": 25, "name": "C#2" ,"description": ""},
            {"noteNumber": 26, "name": "D2" ,"description": ""},
            {"noteNumber": 27, "name": "D#2" ,"description": ""},
            {"noteNumber": 28, "name": "E2" ,"description": ""},
            {"noteNumber": 29, "name": "F2" ,"description": ""},
            {"noteNumber": 30, "name": "F#2" ,"description": ""},
            {"noteNumber": 31, "name": "G2" ,"description": ""},
            {"noteNumber": 32, "name": "G#2" ,"description": ""},
            {"noteNumber": 33, "name": "A2" ,"description": ""},
            {"noteNumber": 34, "name": "A#2" ,"description": ""},
            {"noteNumber": 35, "name": "B2" ,"description": ""},
            {"noteNumber": 36, "name": "C3" ,"description": ""},
            {"noteNumber": 37, "name": "C#3" ,"description": ""},
            {"noteNumber": 38, "name": "D3" ,"description": ""},
            {"noteNumber": 39, "name": "D#3" ,"description": ""},
            {"noteNumber": 40, "name": "E3" ,"description": ""},
            {"noteNumber": 41, "name": "F3" ,"description": ""},
            {"noteNumber": 42, "name": "F#3" ,"description": ""},
            {"noteNumber": 43, "name": "G3" ,"description": ""},
            {"noteNumber": 44, "name": "G#3" ,"description": ""},
            {"noteNumber": 45, "name": "A3" ,"description": ""},
            {"noteNumber": 46, "name": "A#3" ,"description": ""},
            {"noteNumber": 47, "name": "B3" ,"description": ""},
            {"noteNumber": 48, "name": "C4" ,"description": ""},
            {"noteNumber": 49, "name": "C#4" ,"description": ""},
            {"noteNumber": 50, "name": "D4" ,"description": ""},
            {"noteNumber": 51, "name": "D#4" ,"description": ""},
            {"noteNumber": 52, "name": "E4" ,"description": ""},
            {"noteNumber": 53, "name": "F4" ,"description": ""},
            {"noteNumber": 54, "name": "F#4" ,"description": ""},
            {"noteNumber": 55, "name": "G4" ,"description": ""},
            {"noteNumber": 56, "name": "G#4" ,"description": ""},
            {"noteNumber": 57, "name": "A4" ,"description": ""},
            {"noteNumber": 58, "name": "A#4" ,"description": ""},
            {"noteNumber": 59, "name": "B4" ,"description": ""},
            {"noteNumber": 60, "name": "C5" ,"description": ""},
            {"noteNumber": 61, "name": "C#5" ,"description": ""},
            {"noteNumber": 62, "name": "D5" ,"description": ""},
            {"noteNumber": 63, "name": "D#5" ,"description": ""},
            {"noteNumber": 64, "name": "E5" ,"description": ""},
            {"noteNumber": 65, "name": "F5" ,"description": ""},
            {"noteNumber": 66, "name": "F#5" ,"description": ""},
            {"noteNumber": 67, "name": "G5" ,"description": ""},
            {"noteNumber": 68, "name": "G#5" ,"description": ""},
            {"noteNumber": 69, "name": "A5" ,"description": ""},
            {"noteNumber": 70, "name": "A#5" ,"description": ""},
            {"noteNumber": 71, "name": "B5" ,"description": ""},
            {"noteNumber": 72, "name": "C6" ,"description": ""},
            {"noteNumber": 73, "name": "C#6" ,"description": ""},
            {"noteNumber": 74, "name": "D6" ,"description": ""},
            {"noteNumber": 75, "name": "D#6" ,"description": ""},
            {"noteNumber": 76, "name": "E6" ,"description": ""},
            {"noteNumber": 77, "name": "F6" ,"description": ""},
            {"noteNumber": 78, "name": "F#6" ,"description": ""},
            {"noteNumber": 79, "name": "G6" ,"description": ""},
            {"noteNumber": 80, "name": "G#6" ,"description": ""},
            {"noteNumber": 81, "name": "A6" ,"description": ""},
            {"noteNumber": 82, "name": "A#6" ,"description": ""},
            {"noteNumber": 83, "name": "B6" ,"description": ""},
            {"noteNumber": 84, "name": "C7" ,"description": ""},
            {"noteNumber": 85, "name": "C#7" ,"description": ""},
            {"noteNumber": 86, "name": "D7" ,"description": ""},
            {"noteNumber": 87, "name": "D#7" ,"description": ""},
            {"noteNumber": 88, "name": "E7" ,"description": ""},
            {"noteNumber": 89, "name": "F7" ,"description": ""},
            {"noteNumber": 90, "name": "F#7" ,"description": ""},
            {"noteNumber": 91, "name": "G7" ,"description": ""},
            {"noteNumber": 92, "name": "G#7" ,"description": ""},
            {"noteNumber": 93, "name": "A7" ,"description": ""},
            {"noteNumber": 94, "name": "A#7" ,"description": ""},
            {"noteNumber": 95, "name": "B7" ,"description": ""},
            {"noteNumber": 96, "name": "C8" ,"description": ""},
            {"noteNumber": 97, "name": "C#8" ,"description": ""},
            {"noteNumber": 98, "name": "D8" ,"description": ""},
            {"noteNumber": 99, "name": "D#8" ,"description": ""},
            {"noteNumber": 100, "name": "E8" ,"description": ""},
            {"noteNumber": 101, "name": "F8" ,"description": ""},
            {"noteNumber": 102, "name": "F#8" ,"description": ""},
            {"noteNumber": 103, "name": "G8" ,"description": ""},
            {"noteNumber": 104, "name": "G#8" ,"description": ""},
            {"noteNumber": 105, "name": "A8" ,"description": ""},
            {"noteNumber": 106, "name": "A#8" ,"description": ""},
            {"noteNumber": 107, "name": "B8" ,"description": ""},
            {"noteNumber": 108, "name": "C9" ,"description": ""},
            {"noteNumber": 109, "name": "C#9" ,"description": ""},
            {"noteNumber": 110, "name": "D9" ,"description": ""},
            {"noteNumber": 111, "name": "D#9" ,"description": ""},
            {"noteNumber": 112, "name": "E9" ,"description": ""},
            {"noteNumber": 113, "name": "F9" ,"description": ""},
            {"noteNumber": 114, "name": "F#9" ,"description": ""},
            {"noteNumber": 115, "name": "G9" ,"description": ""},
            {"noteNumber": 116, "name": "G#9" ,"description": ""},
            {"noteNumber": 117, "name": "A9" ,"description": ""},
            {"noteNumber": 118, "name": "A#9" ,"description": ""},
            {"noteNumber": 119, "name": "B9" ,"description": ""},
            {"noteNumber": 120, "name": "C10" ,"description": ""},
            {"noteNumber": 121, "name": "C#10" ,"description": ""},
            {"noteNumber": 122, "name": "D10" ,"description": ""},
            {"noteNumber": 123, "name": "D#10" ,"description": ""},
            {"noteNumber": 124, "name": "E10" ,"description": ""},
            {"noteNumber": 125, "name": "F10" ,"description": ""},
            {"noteNumber": 126, "name": "F#10" ,"description": ""},
            {"noteNumber": 127, "name": "G10" ,"description": ""}
            ]
    },
    "GI20": {
        "deviceName": "GI20",
        "description": "Grand Illusions 20 Note mechanism. Unmodified.",
        "paperSpeed": 1,
        "minDistBetweenNotes": 8.0,
        "channelHeight": 3.0,
        "eventHeight": 2.5,
        "eventWidth": 3.0,
        "topPadding": 6.0,
        "rightPadding": 30.0,
        "bottomPadding": 6.0,
        "leftPadding": 30.0,
        "units": "mm",
        "validChannels": [
            {"noteNumber": 60, "name": "C5", "description": ""},
            {"noteNumber": 62, "name": "D5", "description": ""},
            {"noteNumber": 64, "name": "E5", "description": ""},
            {"noteNumber": 65, "name": "F5", "description": ""},
            {"noteNumber": 67, "name": "G5", "description": ""},
            {"noteNumber": 69, "name": "A5", "description": ""},
            {"noteNumber": 71, "name": "B5", "description": ""},
            {"noteNumber": 72, "name": "C6", "description": ""},
            {"noteNumber": 74, "name": "D6", "description": ""},
            {"noteNumber": 76, "name": "E6", "description": ""},
            {"noteNumber": 77, "name": "F6", "description": ""},
            {"noteNumber": 79, "name": "G6", "description": ""},
            {"noteNumber": 81, "name": "A6", "description": ""},
            {"noteNumber": 83, "name": "B6", "description": ""},
            {"noteNumber": 84, "name": "C7", "description": ""},
            {"noteNumber": 86, "name": "D7", "description": ""},
            {"noteNumber": 88, "name": "E7", "description": ""},
            {"noteNumber": 89, "name": "F7", "description": ""},
            {"noteNumber": 91, "name": "G7", "description": ""},
            {"noteNumber": 93, "name": "A7", "description": ""}
        ]
    },
    "GI30": {
        "deviceName": "GI30",
        "description": "Grand Illusions 30 Note mechanism. Unmodified.",
        "paperSpeed": 1,
        "minDistBetweenNotes": 8.0,
        "channelHeight": 1.93,
        "eventHeight": 1.8,
        "eventWidth": 2.0,
        "topPadding": 6.0,
        "rightPadding": 30.0,
        "bottomPadding": 6.0,
        "leftPadding": 30.0,
        "units": "mm",
        "validChannels": [
            {"noteNumber": 53, "name":  "F4", "description": ""},
            {"noteNumber": 55, "name":  "G4", "description": ""},
            {"noteNumber": 60, "name":  "C5", "description": ""},
            {"noteNumber": 62, "name":  "D5", "description": ""},
            {"noteNumber": 64, "name":  "E5", "description": ""},
            {"noteNumber": 65, "name":  "F5", "description": ""},
            {"noteNumber": 67, "name":  "G5", "description": ""},
            {"noteNumber": 69, "name":  "A5", "description": ""},
            {"noteNumber": 70, "name":  "A#5", "description": ""},
            {"noteNumber": 71, "name":  "B5", "description": ""},
            {"noteNumber": 72, "name":  "C6", "description": ""},
            {"noteNumber": 73, "name":  "C#6", "description": ""},
            {"noteNumber": 74, "name":  "D6", "description": ""},
            {"noteNumber": 75, "name":  "D#6", "description": ""},
            {"noteNumber": 76, "name":  "E6", "description": ""},
            {"noteNumber": 77, "name":  "F6", "description": ""},
            {"noteNumber": 78, "name":  "F#6", "description": ""},
            {"noteNumber": 79, "name":  "G6", "description": ""},
            {"noteNumber": 80, "name":  "G#6", "description": ""},
            {"noteNumber": 81, "name":  "A6", "description": ""},
            {"noteNumber": 82, "name":  "A#6", "description": ""},
            {"noteNumber": 83, "name":  "B6", "description": ""},
            {"noteNumber": 84, "name":  "C7", "description": ""},
            {"noteNumber": 85, "name":  "C#7", "description": ""},
            {"noteNumber": 86, "name":  "D7", "description": ""},
            {"noteNumber": 87, "name":  "D#7", "description": ""},
            {"noteNumber": 88, "name":  "E7", "description": ""},
            {"noteNumber": 89, "name":  "F7", "description": ""},
            {"noteNumber": 91, "name":  "G7", "description": ""},
            {"noteNumber": 93, "name":  "A7", "description": ""}
        ]
    },
    "GI15": {
        "deviceName": "GI15",
        "description": "Grand Illusions/Kikkerland 15 Note mechanism. Unmodified.",
        "paperSpeed": 1,
        "minDistBetweenNotes": 8.0,
        "channelHeight": 3.0,
        "eventHeight": 2.5,
        "eventWidth": 3.0,
        "topPadding": 6.0,
        "rightPadding": 30.0,
        "bottomPadding": 6.0,
        "leftPadding": 30.0,
        "units": "mm",
        "validChannels": [
            {"noteNumber": 48, "name":  "C4", "description": ""},
            {"noteNumber": 50, "name":  "D4", "description": ""},
            {"noteNumber": 52, "name":  "E4", "description": ""},
            {"noteNumber": 53, "name":  "F4", "description": ""},
            {"noteNumber": 55, "name":  "G4", "description": ""},
            {"noteNumber": 57, "name":  "A4", "description": ""},
            {"noteNumber": 59, "name":  "B4", "description": ""},
            {"noteNumber": 60, "name":  "C5", "description": ""},
            {"noteNumber": 62, "name":  "D5", "description": ""},
            {"noteNumber": 64, "name":  "E5", "description": ""},
            {"noteNumber": 65, "name":  "F5", "description": ""},
            {"noteNumber": 67, "name":  "G5", "description": ""},
            {"noteNumber": 69, "name":  "A5", "description": ""},
            {"noteNumber": 71, "name":  "B5", "description": ""},
            {"noteNumber": 72, "name":  "C6", "description": ""}
        ]
    },
    "W20AMinor": {
        "deviceName": "20 Channel A minor",
        "descriptions": "Modified 20 note mechanism. A minor",
        "paperSpeed": 1,
        "minDistBetweenNotes": 8.0,
        "channelHeight": 3.0,
        "eventHeight": 2.5,
        "eventWidth": 3.0,
        "topPadding": 6.0,
        "rightPadding": 30.0,
        "bottomPadding": 6.0,
        "leftPadding": 30.0,
        "units": "mm",
        "validChannels": [
            {"noteNumber": 60, "name":  "C5", "description": ""},
            {"noteNumber": 62, "name":  "D5", "description": ""},
            {"noteNumber": 64, "name":  "E5", "description": ""},
            {"noteNumber": 65, "name":  "F5", "description": ""},
            {"noteNumber": 67, "name":  "G5", "description": ""},
            {"noteNumber": 69, "name":  "A5", "description": ""},
            {"noteNumber": 71, "name":  "B5", "description": ""},
            {"noteNumber": 72, "name":  "C6", "description": ""},
            {"noteNumber": 74, "name":  "D6", "description": ""},
            {"noteNumber": 76, "name":  "E6", "description": ""},
            {"noteNumber": 77, "name":  "F6", "description": ""},
            {"noteNumber": 79, "name":  "G6", "description": ""},
            {"noteNumber": 81, "name":  "A6", "description": ""},
            {"noteNumber": 83, "name":  "B6", "description": ""},
            {"noteNumber": 84, "name":  "C7", "description": ""},
            {"noteNumber": 86, "name":  "D7", "description": ""},
            {"noteNumber": 88, "name":  "E7", "description": ""},
            {"noteNumber": 89, "name":  "F7", "description": ""},
            {"noteNumber": 91, "name":  "G7", "description": ""},
            {"noteNumber": 93, "name":  "A7", "description": ""}
        ]
    }
};

